services:
    postgres:
        container_name: todo-app-postgres
        image: postgres:15
        environment:
            POSTGRES_DB: pathway_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"
        volumes:
            - ./init-db:/docker-entrypoint-initdb.d